# GENERAL CONFIGURATION
api-addr: 127.0.0.1:1633
p2p-addr: :1634
debug-api-addr: 127.0.0.1:1635
password-file: /home/bee/.bee/password
data-dir: /home/bee/.bee
# MAINNET CONFIGURATION
bootnode: /dnsaddr/mainnet.ethswarm.org

# ULTRA-LIGHT CONFIGURATION
swap-enable: false
full-node: false
debug-api-enable: true
