services:
    bee-lightnode:
        container_name: bee
        image: ethersphere/bee:stable
        command: start --config /home/bee/.bee.yml
        volumes:
            - ./bee-home-dir:/home/bee
        ports:
            - 1633:1633
            - 1634:1634
            - 1635:1635
        networks:
            - public

    bee-lightnode-dashboard:
        container_name: dashboard
        image: rampall/bee-dashboard
        ports:
            - 8080:8080
        networks:
            - public

networks:
    public:
